table 'Dataflow Permissions'
	lineageTag: ae821948-25a2-40a3-be96-5e2646b20749
	sourceLineageTag: [dbo].[DataflowPermissions]

	measure 'Dataflow Permissions Count' =
			CALCULATE (
			    COUNTROWS('Dataflow Permissions'),
			    'Dataflows'[Dataflow ID] <> "00000000-0000-0000-0000-00000000",
			    USERELATIONSHIP ( 'Dataflow Permissions'[Workspace ID], 'Workspaces'[Workspace ID] ),
			    USERELATIONSHIP ( 'Dataflow Permissions'[Domain ID], 'Domains'[Domain ID] ),
			    USERELATIONSHIP ( 'Dataflow Permissions'[Capacity ID], 'Capacities'[Capacity ID] ),
			    USERELATIONSHIP ( 'Dataflow Permissions'[Deployment Pipeline ID], 'Deployment Pipelines'[Deployment Pipeline ID] ),
			    USERELATIONSHIP ( 'Dataflow Permissions'[Deployment Pipeline Stage ID], 'Deployment Pipeline Stages'[Deployment Pipeline Stage ID] )
			)
		dataType: int64
		formatString: #,0
		lineageTag: 6b58272f-2b7e-4ec6-a3c9-fff1e8ee72f2

	column 'Workspace ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: 0c7901c5-7bee-4c93-baeb-2cafe9737e0d
		sourceLineageTag: WorkspaceID
		summarizeBy: none
		sourceColumn: WorkspaceID

		annotation SummarizationSetBy = Automatic

	column 'Deployment Pipeline ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: 6fae267a-04df-46da-801e-28381168008c
		sourceLineageTag: DeploymentPipelineID
		summarizeBy: none
		sourceColumn: DeploymentPipelineID

		annotation SummarizationSetBy = Automatic

	column 'Deployment Pipeline Stage ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: cf9cab5a-bffb-4126-9241-06f8d6d4fe87
		sourceLineageTag: DeploymentPipelineStageID
		summarizeBy: none
		sourceColumn: DeploymentPipelineStageID

		annotation SummarizationSetBy = Automatic

	column 'Capacity ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: 5555b466-e286-4473-a200-c1c8c162a81b
		sourceLineageTag: CapacityID
		summarizeBy: none
		sourceColumn: CapacityID

		annotation SummarizationSetBy = Automatic

	column 'Domain ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: ccc2a3f9-53a2-449e-b8e0-38264f955eda
		sourceLineageTag: DomainID
		summarizeBy: none
		sourceColumn: DomainID

		annotation SummarizationSetBy = Automatic

	column 'Dataflow ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: 84f309a2-f835-433b-a0f9-349cb9d095cd
		sourceLineageTag: DataflowID
		summarizeBy: none
		sourceColumn: DataflowID

		annotation SummarizationSetBy = Automatic

	column Permissions
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 42cd8f53-342a-4075-bc85-26c57d93d48f
		sourceLineageTag: Permissions
		summarizeBy: none
		sourceColumn: Permissions

		annotation SummarizationSetBy = Automatic

	column 'Email Address'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 54cc6407-e3c1-4eeb-830c-00b7e3a8b1ea
		sourceLineageTag: EmailAddress
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column 'Display Name'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5294945d-cc74-40c0-88d3-54676d5c3b5d
		sourceLineageTag: DisplayName
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column Identifier
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 66702a23-206a-49e3-8452-53d0650f2a73
		sourceLineageTag: Identifier
		summarizeBy: none
		sourceColumn: Identifier

		annotation SummarizationSetBy = Automatic

	column 'Graph ID'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 59f16582-8fd4-42e2-af91-25880da00006
		sourceLineageTag: GraphID
		summarizeBy: none
		sourceColumn: GraphID

		annotation SummarizationSetBy = Automatic

	column 'Principal Type'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c5632b5d-0e1d-45bb-acc4-8b09cc49a3ee
		sourceLineageTag: PrincipalType
		summarizeBy: none
		sourceColumn: PrincipalType

		annotation SummarizationSetBy = Automatic

	column 'User Type'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: bab04810-bdf5-45e8-89a2-8f9ef2d4ae72
		sourceLineageTag: UserType
		summarizeBy: none
		sourceColumn: UserType

		annotation SummarizationSetBy = Automatic

	partition DataflowPermissions = entity
		mode: directLake
		state: ready
		source
			entityName: DataflowPermissions
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

